//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empleado.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Empleado.Application.Resources.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conflico al agregar el nuevo empleado.
        /// </summary>
        public static string EmpleadoServicioConflictAdd {
            get {
                return ResourceManager.GetString("EmpleadoServicioConflictAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conflico al eliminar el empleado ingresado.
        /// </summary>
        public static string EmpleadoServicioConflictDelete {
            get {
                return ResourceManager.GetString("EmpleadoServicioConflictDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conflicto al actualizar datos del empleado.
        /// </summary>
        public static string EmpleadoServicioConflictUpdate {
            get {
                return ResourceManager.GetString("EmpleadoServicioConflictUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron empleplados..
        /// </summary>
        public static string EmpleadoServicioNotFoundActiveNoActiveOk {
            get {
                return ResourceManager.GetString("EmpleadoServicioNotFoundActiveNoActiveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron lista de empleados.
        /// </summary>
        public static string EmpleadoServicioNotFoundAll {
            get {
                return ResourceManager.GetString("EmpleadoServicioNotFoundAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro el empleado ingresado.
        /// </summary>
        public static string EmpleadoServicioNotFoundById {
            get {
                return ResourceManager.GetString("EmpleadoServicioNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ejecuto correctamente el alta del empleado nuevo.
        /// </summary>
        public static string EmpleadoServicioOkAdd {
            get {
                return ResourceManager.GetString("EmpleadoServicioOkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ejecuto correctamente la eliminacion del empleado.
        /// </summary>
        public static string EmpleadoServicioOkDelete {
            get {
                return ResourceManager.GetString("EmpleadoServicioOkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ejecuto correctamente la baja logica del empleado ingresado.
        /// </summary>
        public static string EmpleadoServicioOkDeleteLogic {
            get {
                return ResourceManager.GetString("EmpleadoServicioOkDeleteLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El empleado ingreso, se obtuvo con exito.
        /// </summary>
        public static string EmpleadoServicioOkFoundById {
            get {
                return ResourceManager.GetString("EmpleadoServicioOkFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ejecuto correctamente la actualizacion del empleado.
        /// </summary>
        public static string EmpleadoServicioOkUpdate {
            get {
                return ResourceManager.GetString("EmpleadoServicioOkUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ejecuto correctamente la actualizacion del estado activo del empleado ingresao.
        /// </summary>
        public static string EmpleadoServicioOkUpdateEstado {
            get {
                return ResourceManager.GetString("EmpleadoServicioOkUpdateEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron registros, con edad mayor a los solicitado.
        /// </summary>
        public static string EmpleadoServicoNotFoundByEdadMayorIgual {
            get {
                return ResourceManager.GetString("EmpleadoServicoNotFoundByEdadMayorIgual", resourceCulture);
            }
        }
    }
}
