//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empleado.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesValidationsEmpleados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesValidationsEmpleados() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Empleado.Application.Resources.MessagesValidationsEmpleados", typeof(MessagesValidationsEmpleados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Apellido permite maximo 15 caracteres.
        /// </summary>
        internal static string ValidationsEmpleadoApellidoMax15Caracteres {
            get {
                return ResourceManager.GetString("ValidationsEmpleadoApellidoMax15Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Apellido no puede ser nulo.
        /// </summary>
        internal static string ValidationsEmpleadoApellidoNulo {
            get {
                return ResourceManager.GetString("ValidationsEmpleadoApellidoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo EMail no puede ser nulo.
        /// </summary>
        internal static string ValidationsEmpleadoEMailNull {
            get {
                return ResourceManager.GetString("ValidationsEmpleadoEMailNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo EMail posee un formato incorrecto.
        /// </summary>
        internal static string ValidationsEmpleadoFormatoEMailIncorrecto {
            get {
                return ResourceManager.GetString("ValidationsEmpleadoFormatoEMailIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo EMail permite maximo 25 caracteres.
        /// </summary>
        internal static string ValidationsEmpleadoMax25Caracteres {
            get {
                return ResourceManager.GetString("ValidationsEmpleadoMax25Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Nombre debe ser distinto al campo Apellido.
        /// </summary>
        internal static string ValidationsEmpleadoNombreDistintoApellidos {
            get {
                return ResourceManager.GetString("ValidationsEmpleadoNombreDistintoApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Nombre permite maximo 15 caracteres.
        /// </summary>
        internal static string ValidationsEmpleadoNombreMax15Caracteres {
            get {
                return ResourceManager.GetString("ValidationsEmpleadoNombreMax15Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Nombre no puede ser nulo.
        /// </summary>
        internal static string ValidationsEmpleadoNombreNulo {
            get {
                return ResourceManager.GetString("ValidationsEmpleadoNombreNulo", resourceCulture);
            }
        }
    }
}
